import { CollectionItem } from "@/types";
import {
  AdunbarinDesc,
  AlheriDesc,
  AloraDesc,
  AmaniDesc,
  AriellaDesc,
  AtofaratiDesc,
  AyomideDesc,
  BabaraDesc,
  DanielleDesc,
  FavorDesc,
  HanaDesc,
  IbukunDesc,
  IfeDesc,
  IlerioluwaDesc,
  IrawoSetDesc,
  IreDesc,
  Isinmi1Desc,
  Isinmi2Desc,
  IyanuDesc,
  IyeDesc,
  KeziahDesc,
  KukuDesc,
  MoremiDesc,
  OneThingDesc,
  OreoluwaDesc,
  ShalomDesc,
  TamaraDesc,
  TirzahDesc,
  ZurielDesc,
} from "./description";

const CDNUrl = "https://d1dapjksca996u.cloudfront.net/public";

export const collectionsData: CollectionItem[] = [
  // ===== Bridals Collection =====
  {
    id: "bridal-1",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-12.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-14.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-8.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-10.JPG` },
      { id: "5", url: `${CDNUrl}/bridals-7.JPG` },
      { id: "6", url: `${CDNUrl}/bridals-4.JPG` },
      { id: "7", url: `${CDNUrl}/bridals-9.JPG` },
      { id: "8", url: `${CDNUrl}/bridals-11.JPG` },
      { id: "9", url: `${CDNUrl}/bridals-18.JPG` },
      { id: "10", url: `${CDNUrl}/bridals-16.JPG` },
      { id: "11", url: `${CDNUrl}/bridals-6.JPG` },
      { id: "12", url: `${CDNUrl}/bridals-15.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-1",
  },
  {
    id: "bridal-2",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-33.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-32.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-37.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-34.JPG` },
      { id: "5", url: `${CDNUrl}/bridals-31.JPG` },
      { id: "6", url: `${CDNUrl}/bridals-5.JPG` },
      { id: "7", url: `${CDNUrl}/bridals-28.JPG` },
      { id: "8", url: `${CDNUrl}/bridals-29.JPG` },
      { id: "9", url: `${CDNUrl}/bridals-30.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-2",
  },
  {
    id: "bridal-3",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-26.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-44.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-27.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-3.JPG` },
      { id: "5", url: `${CDNUrl}/bridals-1.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-3",
  },
  {
    id: "bridal-4",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-42.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-41.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-40.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-38.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-4",
  },
  {
    id: "bridal-5",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-23.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-22.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-24.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-5",
  },
  {
    id: "bridal-6",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-2.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-21.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-43.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-6",
  },

  // ===== Igbatuntun Collection =====
  {
    id: "ire-set",
    media: [
      { id: "1", url: `${CDNUrl}/ire-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/ire-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/ire-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/ire-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/ire-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/ire-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/ire-set-7.jpg` },
    ],
    title: "IRE SET",
    category: "Igbatuntun Collection",
    description: <IreDesc />,
    link: "igbatuntun-collection/ire-set",
  },
  {
    id: "amani-dress",
    media: [
      { id: "1", url: `${CDNUrl}/amani-1.jpg` },
      { id: "2", url: `${CDNUrl}/amani-2.jpg` },
      { id: "3", url: `${CDNUrl}/amani-3.jpg` },
      { id: "4", url: `${CDNUrl}/amani-4.jpg` },
      { id: "5", url: `${CDNUrl}/amani-5.jpg` },
      { id: "6", url: `${CDNUrl}/amani-6.jpg` },
      { id: "7", url: `${CDNUrl}/amani-7.jpg` },
      { id: "8", url: `${CDNUrl}/amani-8.jpg` },
      { id: "9", url: `${CDNUrl}/amani-9.jpg` },
      { id: "10", url: `${CDNUrl}/amani-10.jpg` },
      { id: "11", url: `${CDNUrl}/amani-11.jpg` },
    ],
    title: "AMANI DRESS",
    category: "Igbatuntun Collection",
    description: <AmaniDesc />,
    link: "igbatuntun-collection/amani-dress",
  },
  {
    id: "ayomide-set",
    media: [
      { id: "1", url: `${CDNUrl}/ayomide-1.jpg` },
      { id: "2", url: `${CDNUrl}/ayomide-2.jpg` },
      { id: "3", url: `${CDNUrl}/ayomide-3.jpg` },
      { id: "4", url: `${CDNUrl}/ayomide-4.jpg` },
      { id: "5", url: `${CDNUrl}/ayomide-5.jpg` },
      { id: "6", url: `${CDNUrl}/ayomide-6.jpg` },
      { id: "7", url: `${CDNUrl}/ayomide-7.jpg` },
      { id: "8", url: `${CDNUrl}/ayomide-8.jpg` },
      { id: "9", url: `${CDNUrl}/ayomide-9.jpg` },
      { id: "10", url: `${CDNUrl}/ayomide-10.jpg` },
    ],
    title: "AYOMIDE SET",
    category: "Igbatuntun Collection",
    description: <AyomideDesc />,
    link: "igbatuntun-collection/ayomide-set",
  },
  {
    id: "favor-set",
    media: [
      { id: "1", url: `${CDNUrl}/favor-1.jpg` },
      { id: "2", url: `${CDNUrl}/favor-2.jpg` },
    ],
    title: "FAVOR SET",
    category: "Igbatuntun Collection",
    description: <FavorDesc />,
    link: "igbatuntun-collection/favor-set",
  },
  {
    id: "ibukun-set",
    media: [
      { id: "1", url: `${CDNUrl}/ibukun-1.jpeg` },
      { id: "2", url: `${CDNUrl}/ibukun-2.jpeg` },
      { id: "3", url: `${CDNUrl}/ibukun-3.jpeg` },
      { id: "4", url: `${CDNUrl}/ibukun-4.jpeg` },
    ],
    title: "IBUKUN SET",
    category: "Igbatuntun Collection",
    description: <IbukunDesc />,
    link: "igbatuntun-collection/ibukun-set",
  },
  {
    id: "ife-set",
    media: [
      { id: "1", url: `${CDNUrl}/ife-1.jpg` },
      { id: "2", url: `${CDNUrl}/ife-2.jpg` },
      { id: "3", url: `${CDNUrl}/ife-3.jpg` },
      { id: "4", url: `${CDNUrl}/ife-4.jpg` },
      { id: "5", url: `${CDNUrl}/ife-5.jpg` },
      { id: "6", url: `${CDNUrl}/ife-6.jpg` },
      { id: "7", url: `${CDNUrl}/ife-7.jpg` },
      { id: "8", url: `${CDNUrl}/ife-8.jpg` },
      { id: "9", url: `${CDNUrl}/ife-9.jpg` },
      { id: "10", url: `${CDNUrl}/ife-10.jpg` },
      { id: "11", url: `${CDNUrl}/ife-11.jpg` },
    ],
    title: "IFE SET",
    category: "Igbatuntun Collection",
    description: <IfeDesc />,
    link: "igbatuntun-collection/ife-set",
  },
  {
    id: "irawo-dress",
    media: [
      { id: "1", url: `${CDNUrl}/irawo-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/irawo-dress-2.jpg` },
    ],
    title: "IRAWO DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/irawo-dress",
  },
  {
    id: "irawo-set",
    media: [
      { id: "1", url: `${CDNUrl}/irawo-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/irawo-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/irawo-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/irawo-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/irawo-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/irawo-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/irawo-set-7.jpg` },
      { id: "8", url: `${CDNUrl}/irawo-set-8.jpg` },
      { id: "9", url: `${CDNUrl}/irawo-set-9.jpg` },
      { id: "10", url: `${CDNUrl}/irawo-set-10.jpg` },
    ],
    title: "IRAWO SET",
    category: "Igbatuntun Collection",
    description: <IrawoSetDesc />,
    link: "igbatuntun-collection/irawo-set",
  },
  {
    id: "iyanu-dress",
    media: [
      { id: "1", url: `${CDNUrl}/iyanu-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/iyanu-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/iyanu-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/iyanu-dress-4.jpg` },
      { id: "5", url: `${CDNUrl}/iyanu-dress-5.jpg` },
      { id: "6", url: `${CDNUrl}/iyanu-dress-6.jpg` },
      { id: "7", url: `${CDNUrl}/iyanu-dress-7.jpg` },
      { id: "8", url: `${CDNUrl}/iyanu-dress-8.jpg` },
      { id: "9", url: `${CDNUrl}/iyanu-dress-9.jpg` },
      { id: "10", url: `${CDNUrl}/iyanu-dress-10.jpg` },
      { id: "11", url: `${CDNUrl}/iyanu-dress-11.jpg` },
    ],
    title: "IYANU DRESS",
    category: "Igbatuntun Collection",
    description: <IyanuDesc />,
    link: "igbatuntun-collection/iyanu-dress",
  },
  {
    id: "kuku-set",
    media: [
      { id: "1", url: `${CDNUrl}/kuku-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/kuku-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/kuku-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/kuku-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/kuku-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/kuku-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/kuku-set-7.jpg` },
      { id: "8", url: `${CDNUrl}/kuku-set-8.jpg` },
      { id: "9", url: `${CDNUrl}/kuku-set-9.jpg` },
      { id: "10", url: `${CDNUrl}/kuku-set-10.jpg` },
    ],
    title: "KUKU SET",
    category: "Igbatuntun Collection",
    description: <KukuDesc />,
    link: "igbatuntun-collection/kuku-set",
  },
  {
    id: "oreoluwa-dress",
    media: [
      { id: "1", url: `${CDNUrl}/oreoluwa-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/oreoluwa-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/oreoluwa-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/oreoluwa-dress-4.jpg` },
      { id: "5", url: `${CDNUrl}/oreoluwa-dress-5.jpg` },
      { id: "6", url: `${CDNUrl}/oreoluwa-dress-6.jpg` },
      { id: "7", url: `${CDNUrl}/oreoluwa-dress-7.jpg` },
    ],
    title: "OREOLUWA DRESS",
    category: "Igbatuntun Collection",
    description: <OreoluwaDesc />,
    link: "igbatuntun-collection/oreoluwa-dress",
  },
  {
    id: "one-thing",
    media: [
      { id: "1", url: `${CDNUrl}/one-thing-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/one-thing-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/one-thing-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/one-thing-dress-4.jpg` },
      { id: "5", url: `${CDNUrl}/one-thing-dress-5.jpg` },
      { id: "6", url: `${CDNUrl}/one-thing-dress-6.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-7.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-8.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-9.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-10.jpg` },
    ],
    title: "ONE THING DRESS",
    category: "Igbatuntun Collection",
    description: <OneThingDesc />,
    link: "igbatuntun-collection/one-thing",
  },
  {
    id: "isinmi-1-dress",
    media: [
      { id: "1", url: `${CDNUrl}/isinmi-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/isinmi-dress-5.jpg` },
      { id: "3", url: `${CDNUrl}/isinmi-dress-6.jpg` },
      { id: "4", url: `${CDNUrl}/isinmi-dress-8.jpg` },
      { id: "5", url: `${CDNUrl}/isinmi-dress-10.jpg` },
      { id: "6", url: `${CDNUrl}/isinmi-dress-11.jpg` },
      { id: "7", url: `${CDNUrl}/isinmi-dress-12.jpg` },
      { id: "8", url: `${CDNUrl}/isinmi-dress-15.jpg` },
      { id: "9", url: `${CDNUrl}/isinmi-dress-17.jpg` },
      { id: "10", url: `${CDNUrl}/isinmi-dress-18.jpg` },
      { id: "11", url: `${CDNUrl}/isinmi-dress-20.jpg` },
    ],
    title: "ISINMI 1 DRESS",
    category: "Igbatuntun Collection",
    description: <Isinmi1Desc />,
    link: "igbatuntun-collection/isinmi-1-dress",
  },
  {
    id: "isinmi-2-dress",
    media: [
      { id: "2", url: `${CDNUrl}/isinmi-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/isinmi-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/isinmi-dress-4.jpg` },
      { id: "7", url: `${CDNUrl}/isinmi-dress-7.jpg` },
      { id: "9", url: `${CDNUrl}/isinmi-dress-9.jpg` },
      { id: "13", url: `${CDNUrl}/isinmi-dress-13.jpg` },
      { id: "14", url: `${CDNUrl}/isinmi-dress-14.jpg` },
      { id: "16", url: `${CDNUrl}/isinmi-dress-16.jpg` },
      { id: "19", url: `${CDNUrl}/isinmi-dress-19.jpg` },
      { id: "21", url: `${CDNUrl}/isinmi-dress-21.jpg` },
    ],
    title: "ISINMI 2 DRESS",
    category: "Igbatuntun Collection",
    description: <Isinmi2Desc />,
    link: "igbatuntun-collection/isinmi-2-dress",
  },

  // ===== Nuach Collection =====
  {
    id: "adunbarin-set",
    media: [
      { id: "1", url: `${CDNUrl}/adunbarin-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/adunbarin-1.jpg` },
      { id: "3", url: `${CDNUrl}/adunbarin-2.jpg` },
      { id: "4", url: `${CDNUrl}/adunbarin-3.jpg` },
      { id: "5", url: `${CDNUrl}/adunbarin-4.jpg` },
      { id: "6", url: `${CDNUrl}/adunbarin-5.jpg` },
      { id: "7", url: `${CDNUrl}/adunbarin-6.jpg` },
      { id: "8", url: `${CDNUrl}/adunbarin-7.jpg` },
    ],
    title: "ADUNBARIN SET",
    category: "Nuach Collection",
    description: <AdunbarinDesc />,
    link: "nuach/adunbarin-set",
    price: 57000,
  },
  {
    id: "alheri-set",
    media: [
      { id: "1", url: `${CDNUrl}/alheri-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/alheri-1.png` },
      { id: "3", url: `${CDNUrl}/alheri-2.jpeg` },
      { id: "4", url: `${CDNUrl}/alheri-3.png` },
      { id: "5", url: `${CDNUrl}/alheri-4.png` },
      { id: "6", url: `${CDNUrl}/alheri-5.png` },
      { id: "7", url: `${CDNUrl}/alheri-6.png` },
    ],
    title: "ALHERI SET",
    category: "Nuach Collection",
    description: <AlheriDesc />,
    link: "nuach/alheri-set",
    price: 49000,
  },
  {
    id: "alora-dress",
    media: [
      { id: "1", url: `${CDNUrl}/alora-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/alora-3.png` },
      { id: "3", url: `${CDNUrl}/alora-4.png` },
      { id: "4", url: `${CDNUrl}/alora-2.png` },
      { id: "5", url: `${CDNUrl}/alora-1.png` },
      { id: "6", url: `${CDNUrl}/alora-5.png` },
      { id: "7", url: `${CDNUrl}/alora-6.png` },
    ],
    title: "ALORA DRESS",
    category: "Nuach Collection",
    description: <AloraDesc />,
    link: "nuach/alora-dress",
    price: 55000,
  },
  {
    id: "ariella-dress",
    media: [
      { id: "1", url: `${CDNUrl}/ariella-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/ariella-1.png` },
      { id: "3", url: `${CDNUrl}/ariella-2.png` },
      { id: "4", url: `${CDNUrl}/ariella-3.png` },
      { id: "5", url: `${CDNUrl}/ariella-4.png` },
      { id: "6", url: `${CDNUrl}/ariella-5.png` },
      { id: "7", url: `${CDNUrl}/ariella-6.png` },
      { id: "8", url: `${CDNUrl}/ariella-7.png` },
    ],
    title: "ARIELLA DRESS",
    category: "Nuach Collection",
    description: <AriellaDesc />,
    link: "nuach/ariella-dress",
    price: 60500,
  },
  {
    id: "atofarati-set",
    media: [
      { id: "1", url: `${CDNUrl}/atofarati-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/atofarati-1.png` },
      { id: "3", url: `${CDNUrl}/atofarati-2.png` },
      { id: "4", url: `${CDNUrl}/atofarati-3.png` },
      { id: "5", url: `${CDNUrl}/atofarati-4.png` },
      { id: "6", url: `${CDNUrl}/atofarati-5.png` },
      { id: "7", url: `${CDNUrl}/atofarati-6.png` },
      { id: "8", url: `${CDNUrl}/atofarati-7.png` },
      { id: "9", url: `${CDNUrl}/atofarati-8.png` },
      { id: "10", url: `${CDNUrl}/atofarati-9.png` },
      { id: "11", url: `${CDNUrl}/atofarati-10.png` },
    ],
    title: "ATOFARATI SET",
    category: "Nuach Collection",
    description: <AtofaratiDesc />,
    link: "nuach/atofarati-set",
    priceVariations: [
      { style: "Adire and Asooke", price: 53000 },
      { style: "Asooke and Taffeta", price: 56000 },
      { style: "2 Colored Taffeta", price: 50000 },
      { style: "Full Asooke", price: 85000 },
    ],
  },
  {
    id: "babara-dress",
    media: [
      { id: "1", url: `${CDNUrl}/barabara-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/barabara-1.jpeg` },
      { id: "3", url: `${CDNUrl}/barabara-2.png` },
      { id: "4", url: `${CDNUrl}/barabara-3.png` },
      { id: "5", url: `${CDNUrl}/barabara-4.png` },
      { id: "6", url: `${CDNUrl}/barabara-5.png` },
      { id: "7", url: `${CDNUrl}/barabara-6.png` },
      { id: "8", url: `${CDNUrl}/barabara-7.png` },
      { id: "9", url: `${CDNUrl}/barabara-8.png` },
      { id: "10", url: `${CDNUrl}/barabara-9.png` },
      { id: "11", url: `${CDNUrl}/barabara-10.png` },
    ],
    title: "BABARA DRESS",
    category: "Nuach Collection",
    description: <BabaraDesc />,
    link: "nuach/babara-dress",
    priceVariations: [
      { style: "Flowered Mikado", price: 63000 },
      { style: "Adire Cotton", price: 52000 },
      { style: "Adire Crepe", price: 52000 },
    ],
  },
  {
    id: "danielle-set",
    media: [
      { id: "1", url: `${CDNUrl}/danielle-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/danielle-1.png` },
      { id: "3", url: `${CDNUrl}/danielle-2.png` },
      { id: "4", url: `${CDNUrl}/danielle-3.png` },
      { id: "5", url: `${CDNUrl}/danielle-4.png` },
      { id: "6", url: `${CDNUrl}/danielle-5.png` },
      { id: "7", url: `${CDNUrl}/danielle-6.png` },
      { id: "8", url: `${CDNUrl}/danielle-7.png` },
      { id: "9", url: `${CDNUrl}/danielle-8.jpeg` },
      { id: "10", url: `${CDNUrl}/danielle-9.png` },
      { id: "11", url: `${CDNUrl}/danielle-10.png` },
    ],
    title: "DANIELLE SET",
    category: "Nuach Collection",
    description: <DanielleDesc />,
    link: "nuach/danielle-set",
    priceVariations: [
      { style: "Dress Set", price: 76000 },
      { style: "Skirt Set", price: 61500 },
    ],
  },
  {
    id: "ileri-boubou",
    media: [
      { id: "1", url: `${CDNUrl}/ileri-boubou-1.mp4` },
      { id: "2", url: `${CDNUrl}/ilerioluwa-1.png` },
      { id: "3", url: `${CDNUrl}/ilerioluwa-2.png` },
      { id: "4", url: `${CDNUrl}/ilerioluwa-3.png` },
      { id: "5", url: `${CDNUrl}/ilerioluwa-4.png` },
      { id: "6", url: `${CDNUrl}/ilerioluwa-5.png` },
    ],
    title: "ILERIOLUWA SET/BOUBOU",
    category: "Nuach Collection",
    description: <IlerioluwaDesc />,
    link: "nuach/ileri-boubou",
    priceVariations: [
      { style: "Set", price: 53000 },
      { style: "Boubou in Mikado", price: 38500 },
      { style: "Boubou in Adire", price: 40000 },
    ],
  },
  {
    id: "iye-dress",
    media: [
      { id: "1", url: `${CDNUrl}/iye-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/iye-1.png` },
      { id: "3", url: `${CDNUrl}/iye-2.png` },
      { id: "4", url: `${CDNUrl}/iye-3.png` },
      { id: "5", url: `${CDNUrl}/iye-4.png` },
      { id: "6", url: `${CDNUrl}/iye-5.png` },
      { id: "7", url: `${CDNUrl}/iye-6.png` },
      { id: "8", url: `${CDNUrl}/iye-7.png` },
      { id: "9", url: `${CDNUrl}/iye-8.png` },
      { id: "10", url: `${CDNUrl}/iye-9.png` },
      { id: "11", url: `${CDNUrl}/iye-10.png` },
      { id: "12", url: `${CDNUrl}/iye-11.png` },
      { id: "13", url: `${CDNUrl}/iye-12.png` },
    ],
    title: "IYE DRESS",
    category: "Nuach Collection",
    description: <IyeDesc />,
    link: "nuach/iye-dress",
    priceVariations: [
      { style: "Fitted (Plain Color)", price: 51000 },
      { style: "Fitted (Adire)", price: 52500 },
      { style: "Flair (Adire)", price: 62000 },
    ],
  },
  {
    id: "keziah-set",
    media: [
      { id: "1", url: `${CDNUrl}/keziah-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/keziah-1.png` },
      { id: "3", url: `${CDNUrl}/keziah-2.png` },
      { id: "4", url: `${CDNUrl}/keziah-3.png` },
      { id: "5", url: `${CDNUrl}/keziah-4.png` },
      { id: "6", url: `${CDNUrl}/keziah-5.png` },
      { id: "7", url: `${CDNUrl}/keziah-6.png` },
      { id: "8", url: `${CDNUrl}/keziah-7.png` },
      { id: "9", url: `${CDNUrl}/keziah-8.png` },
      { id: "10", url: `${CDNUrl}/keziah-9.png` },
      { id: "11", url: `${CDNUrl}/keziah-10.png` },
    ],
    title: "KEZIAH SET",
    category: "Nuach Collection",
    description: <KeziahDesc />,
    link: "nuach/keziah-set",
    priceVariations: [
      { style: "2 Colored Taffeta", price: 51500 },
      { style: "Adire (Pant Set)", price: 50500 },
      { style: "Adire (Skirt Set)", price: 49000 },
      { style: "Plain Color (Pant Set)", price: 48000 },
    ],
  },
  {
    id: "shalom-set",
    media: [
      { id: "1", url: `${CDNUrl}/shalom-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/shalom-1.png` },
      { id: "3", url: `${CDNUrl}/shalom-2.png` },
      { id: "4", url: `${CDNUrl}/shalom-3.png` },
      { id: "5", url: `${CDNUrl}/shalom-4.png` },
      { id: "6", url: `${CDNUrl}/shalom-5.png` },
    ],
    title: "SHALOM SET",
    category: "Nuach Collection",
    description: <ShalomDesc />,
    link: "nuach/shalom-set",
    priceVariations: [
      { style: "In Adire", price: 55000 },
      { style: "Plain Color & Sunray", price: 52000 },
    ],
  },
  {
    id: "tamara-dress",
    media: [
      { id: "1", url: `${CDNUrl}/tamara-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/tamara-1.jpg` },
      { id: "3", url: `${CDNUrl}/tamara-3.jpg` },
      { id: "4", url: `${CDNUrl}/tamara-2.jpg` },
    ],
    title: "TAMARA DRESS",
    category: "Nuach Collection",
    description: <TamaraDesc />,
    link: "nuach/tamara-dress",
    price: 42000,
  },
  {
    id: "tirzah-dress",
    media: [
      { id: "1", url: `${CDNUrl}/tirzah-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/tirzah-1.png` },
      { id: "3", url: `${CDNUrl}/tirzah-2.png` },
      { id: "4", url: `${CDNUrl}/tirzah-3.png` },
      { id: "5", url: `${CDNUrl}/tirzah-4.png` },
      { id: "6", url: `${CDNUrl}/tirzah-5.png` },
      { id: "7", url: `${CDNUrl}/tirzah-6.png` },
      { id: "8", url: `${CDNUrl}/tirzah-7.png` },
      { id: "9", url: `${CDNUrl}/tirzah-8.png` },
      { id: "10", url: `${CDNUrl}/tirzah-9.png` },
      { id: "11", url: `${CDNUrl}/tirzah-10.png` },
      { id: "12", url: `${CDNUrl}/tirzah-11.png` },
    ],
    title: "TIRZAH DRESS",
    category: "Nuach Collection",
    description: <TirzahDesc />,
    link: "nuach/tirzah-dress",
    priceVariations: [
      { style: "Plain Color Long Dress", price: 60000 },
      { style: "Adire Silk", price: 55000 },
      { style: "Adire Crepe Boubou", price: 41500 },
    ],
  },
  {
    id: "hana-set",
    media: [
      { id: "1", url: `${CDNUrl}/hana-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/hana-1.jpg` },
      { id: "3", url: `${CDNUrl}/hana-2.jpg` },
      { id: "4", url: `${CDNUrl}/hana-3.jpg` },
      { id: "5", url: `${CDNUrl}/hana-4.jpg` },
      { id: "6", url: `${CDNUrl}/hana-5.jpg` },
      { id: "7", url: `${CDNUrl}/hana-6.jpg` },
    ],
    title: "HANA SET",
    category: "Nuach Collection",
    description: <HanaDesc />,
    link: "nuach/hana-set",
    price: 67000,
  },

  {
    id: "moremi-set",
    media: [
      { id: "1", url: `${CDNUrl}/moremi-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/moremi-1.jpg` },
      { id: "3", url: `${CDNUrl}/moremi-2.jpg` },
      { id: "4", url: `${CDNUrl}/moremi-3.jpg` },
      { id: "5", url: `${CDNUrl}/moremi-4.jpg` },
      { id: "6", url: `${CDNUrl}/moremi-5.jpg` },
    ],
    title: "MOREMI SET",
    category: "Nuach Collection",
    description: <MoremiDesc />,
    link: "nuach/moremi-set",
    price: 50000,
  },

  {
    id: "zuriel-set",
    media: [
      { id: "1", url: `${CDNUrl}/zuriel-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/zuriel-1.jpg` },
      { id: "3", url: `${CDNUrl}/zuriel-3.jpg` },
      { id: "4", url: `${CDNUrl}/zuriel-2.jpg` },
      { id: "5", url: `${CDNUrl}/zuriel-5.jpg` },
      { id: "6", url: `${CDNUrl}/zuriel-4.jpg` },
      { id: "7", url: `${CDNUrl}/zuriel-6.jpg` },
      { id: "8", url: `${CDNUrl}/zuriel-7.jpg` },
    ],
    title: "ZURIEL SET",
    category: "Nuach Collection",
    description: <ZurielDesc />,
    link: "nuach/zuriel-set",
    priceVariations: [
      { style: "Embellished Crepe", price: 52000 },
      { style: "Plain and Adire Pants", price: 45000 },
    ],
  },
];
