import { CollectionItem } from "@/types";
import {
  AdunbarinDesc,
  AlheriDesc,
  AloraDesc,
  AmaniDesc,
  AriellaDesc,
  AtofaratiDesc,
  AyomideDesc,
  BabaraDesc,
  BeulaDesc,
  DanielleDesc,
  EdenDesc,
  EwaBouBouDesc,
  EwaDesc,
  FavorDesc,
  HanaDesc,
  IbukunDesc,
  IfeDesc,
  IlerioluwaDesc,
  IrawoSetDesc,
  IreDesc,
  Isinmi1Desc,
  Isinmi2Desc,
  IyanuDesc,
  IyeDesc,
  KeziahDesc,
  KukuDesc,
  MoremiDesc,
  OneThingDesc,
  OreoluwaDesc,
  ShalomDesc,
  TamaraDesc,
  TirzahDesc,
  ZaharaDesc,
  ZurielDesc,
  MirabelDesc,
  AyoDesc,
  SharonDesc,
  AdukeDesc,
  ExtraOrdinaryDesc,
  Adire2in1Desc,
  AdireVelvetyDesc,
  LaNouvelleDesc,
  AdebisiDesc,
} from "./description";

const CDNUrl = process.env.NEXT_PUBLIC_CDN_URL;

export const collectionsData: CollectionItem[] = [
  // ===== Bridals Collection =====
  {
    id: "bridal-1",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-12.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-14.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-8.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-10.JPG` },
      { id: "5", url: `${CDNUrl}/bridals-7.JPG` },
      { id: "6", url: `${CDNUrl}/bridals-4.JPG` },
      { id: "7", url: `${CDNUrl}/bridals-9.JPG` },
      { id: "8", url: `${CDNUrl}/bridals-11.JPG` },
      { id: "9", url: `${CDNUrl}/bridals-18.JPG` },
      { id: "10", url: `${CDNUrl}/bridals-16.JPG` },
      { id: "11", url: `${CDNUrl}/bridals-6.JPG` },
      { id: "12", url: `${CDNUrl}/bridals-15.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-1",
  },
  {
    id: "bridal-2",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-33.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-32.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-37.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-34.JPG` },
      { id: "5", url: `${CDNUrl}/bridals-31.JPG` },
      { id: "6", url: `${CDNUrl}/bridals-5.JPG` },
      { id: "7", url: `${CDNUrl}/bridals-28.JPG` },
      { id: "8", url: `${CDNUrl}/bridals-29.JPG` },
      { id: "9", url: `${CDNUrl}/bridals-30.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-2",
  },
  {
    id: "bridal-3",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-26.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-44.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-27.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-3.JPG` },
      { id: "5", url: `${CDNUrl}/bridals-1.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-3",
  },
  {
    id: "bridal-4",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-42.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-41.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-40.JPG` },
      { id: "4", url: `${CDNUrl}/bridals-38.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-4",
  },
  {
    id: "bridal-5",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-23.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-22.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-24.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-5",
  },
  {
    id: "bridal-6",
    media: [
      { id: "1", url: `${CDNUrl}/bridals-2.JPG` },
      { id: "2", url: `${CDNUrl}/bridals-21.JPG` },
      { id: "3", url: `${CDNUrl}/bridals-43.JPG` },
    ],
    title: "BRIDALS BY THEABIKEWOMAN",
    category: "Bridals",
    description: "BRIDALS BY THEABIKEWOMAN",
    link: "bridals/bridal-6",
  },
  {
    id: "eden-dress",
    media: [
      { id: "1",  url: `${CDNUrl}/eden.mp4` },
      { id: "2",  url: `${CDNUrl}/eden-dress-7.jpg` },
      { id: "3",  url: `${CDNUrl}/eden-dress-3.jpg` },
      { id: "4",  url: `${CDNUrl}/eden-dress-11.jpg` },
      { id: "5",  url: `${CDNUrl}/eden-dress-1.jpg` },
      { id: "6",  url: `${CDNUrl}/eden-dress-9.jpg` },
      { id: "7",  url: `${CDNUrl}/eden-dress-5.jpg` },
      { id: "8",  url: `${CDNUrl}/eden-dress-12.jpg` },
      { id: "9",  url: `${CDNUrl}/eden-dress-2.jpg` },
      { id: "10", url: `${CDNUrl}/eden-dress-8.jpg` },
      { id: "11", url: `${CDNUrl}/eden-dress-4.jpg` },
      { id: "12", url: `${CDNUrl}/eden-dress-10.jpg` },
      { id: "13", url: `${CDNUrl}/eden-dress-6.jpg` },
    ],
    title: "EDEN DRESS",
    category: "Bridals",
    description: <EdenDesc />,
    link: "bridals/eden-dress",
  },
  {
    id: "beulah-dress",
    media: [
      { id: "1", url: `${CDNUrl}/beulah.mp4` },
      { id: "2", url: `${CDNUrl}/beulah-dress-4.jpg` },
      { id: "3", url: `${CDNUrl}/beulah-dress-1.jpg` },
      { id: "4", url: `${CDNUrl}/beulah-dress-6.jpg` },
      { id: "5", url: `${CDNUrl}/beulah-dress-2.jpg` },
      { id: "6", url: `${CDNUrl}/beulah-dress-5.jpg` },
      { id: "7", url: `${CDNUrl}/beulah-dress-3.jpg` },
    ],
    title: "BEULAH DRESS",
    category: "Bridals",
    description: <BeulaDesc />,
    link: "bridals/beulah-dress",
  },
  {
    id: "zahara-dress",
    media: [
      { id: "1", url: `${CDNUrl}/zahara.mp4` },
    ],
    title: "ZAHARA DRESS",
    category: "Bridals",
    description: <ZaharaDesc />,
    link: "bridals/zahara-dress",
  },
  {
    id: "sharon-dress",
    media: [
      { id: "1", url: `${CDNUrl}/sharon-dress-1.png` },
      { id: "2", url: `${CDNUrl}/sharon-dress-2.png` },
      { id: "3", url: `${CDNUrl}/sharon-dress-3.png` },
      { id: "4", url: `${CDNUrl}/sharon-dress-4.png` },
      { id: "5", url: `${CDNUrl}/sharon-dress-5.png` },
      { id: "6", url: `${CDNUrl}/sharon-dress-6.png` },
      { id: "7", url: `${CDNUrl}/sharon-dress-7.png` },
      { id: "8", url: `${CDNUrl}/sharon-dress-8.png` },
      { id: "9", url: `${CDNUrl}/sharon-dress-9.png` },
    ],
    title: "SHARON DRESS",
    category: "Bridals",
    description: <SharonDesc />,
    link: "bridals/sharon-dress",
  },

  // ===== Igbatuntun Collection =====
  {
    id: "aduke-set",
    media: [
      { id: "1", url: `${CDNUrl}/aduke-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/aduke-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/aduke-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/aduke-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/aduke-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/aduke-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/aduke-set-7.jpg` },
      { id: "8", url: `${CDNUrl}/aduke-set-8.jpg` },
      { id: "9", url: `${CDNUrl}/aduke-set-9.jpg` },
      { id: "10", url: `${CDNUrl}/aduke-set-10.jpg` },
    ],
    title: "ADUKE SET",
    category: "Igbatuntun Collection",
    description: <AdukeDesc />,
    link: "igbatuntun/aduke-set",
    priceVariations: [
      { style: "Aduke Set", price: 60000, priceGBP: undefined, priceCAD: 65 },
      { style: "Aduke Silk Set", price: 60000, priceGBP: undefined, priceCAD: 65 },
      { style: "Aduke 2 Colored Set", price: 60000, priceGBP: undefined, priceCAD: 65 },
    ],
  },
  {
    id: "extra-ordinary-set",
    media: [
      { id: "1", url: `${CDNUrl}/extra-ordinary-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/extra-ordinary-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/extra-ordinary-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/extra-ordinary-set-4.jpg` },
    ],
    title: "EXTRA ORDINARY SET",
    category: "Igbatuntun Collection",
    description: <ExtraOrdinaryDesc />,
    link: "igbatuntun/extra-ordinary-set",
    price: 55000,
    priceGBP: undefined,
    priceCAD: 55,
  },
  {
    id: "adire-2in1-set",
    media: [
      { id: "1", url: `${CDNUrl}/adire-2in1-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/adire-2in1-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/adire-2in1-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/adire-2in1-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/adire-2in1-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/adire-2in1-set-6.jpg` },
    ],
    title: "ADIRE 2 IN 1 SET",
    category: "Igbatuntun Collection",
    description: <Adire2in1Desc />,
    link: "igbatuntun/adire-2in1-set",
    price: 60000,
    priceGBP: undefined,
    priceCAD: 65,
  },
  {
    id: "adire-velvety",
    media: [
      { id: "1", url: `${CDNUrl}/adire-velvety-1.jpg` },
      { id: "2", url: `${CDNUrl}/adire-velvety-2.jpg` },
      { id: "3", url: `${CDNUrl}/adire-velvety-3.jpg` },
      { id: "4", url: `${CDNUrl}/adire-velvety-4.jpg` },
      { id: "5", url: `${CDNUrl}/adire-velvety-5.jpg` },
    ],
    title: "ADIRE VELVETY",
    category: "Igbatuntun Collection",
    description: <AdireVelvetyDesc />,
    link: "igbatuntun/adire-velvety",
    price: 60000,
    priceGBP: undefined,
    priceCAD: 65,
  },
  {
    id: "la-nouvelle-jumpsuit",
    media: [
      { id: "1", url: `${CDNUrl}/la-nouvelle-jumpsuit-1.jpg` },
      { id: "2", url: `${CDNUrl}/la-nouvelle-jumpsuit-2.jpg` },
      { id: "3", url: `${CDNUrl}/la-nouvelle-jumpsuit-3.jpg` },
      { id: "4", url: `${CDNUrl}/la-nouvelle-jumpsuit-4.jpg` },
      { id: "5", url: `${CDNUrl}/la-nouvelle-jumpsuit-5.jpg` },
      { id: "6", url: `${CDNUrl}/la-nouvelle-jumpsuit-6.jpg` },
    ],
    title: "LA NOUVELLE JUMPSUIT",
    category: "Igbatuntun Collection",
    description: <LaNouvelleDesc />,
    link: "igbatuntun/la-nouvelle-jumpsuit",
    price: 48000,
    priceGBP: undefined,
    priceCAD: 54,
  },
  {
    id: "adebisi-boubou",
    media: [
      { id: "1", url: `${CDNUrl}/adebisi-boubou-1.jpg` },
      { id: "2", url: `${CDNUrl}/adebisi-boubou-2.jpg` },
      { id: "3", url: `${CDNUrl}/adebisi-boubou-3.jpg` },
      { id: "4", url: `${CDNUrl}/adebisi-boubou-4.jpg` },
    ],
    title: "ADEBISI BOUBOU",
    category: "Igbatuntun Collection",
    description: <AdebisiDesc />,
    link: "igbatuntun/adebisi-boubou",
    price: 45000,
    priceGBP: undefined,
    priceCAD: 50,
  },
  {
    id: "ire-set",
    media: [
      { id: "1", url: `${CDNUrl}/ire-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/ire-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/ire-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/ire-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/ire-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/ire-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/ire-set-7.jpg` },
    ],
    title: "IRE SET",
    category: "Igbatuntun Collection",
    description: <IreDesc />,
    link: "igbatuntun-collection/ire-set",
    price: 60000,
    priceGBP: undefined,
    priceCAD: 65,
  },
  {
    id: "amani-dress",
    media: [
      { id: "1", url: `${CDNUrl}/amani-1.jpg` },
      { id: "2", url: `${CDNUrl}/amani-2.jpg` },
      { id: "3", url: `${CDNUrl}/amani-3.jpg` },
      { id: "4", url: `${CDNUrl}/amani-4.jpg` },
      { id: "5", url: `${CDNUrl}/amani-5.jpg` },
      { id: "6", url: `${CDNUrl}/amani-6.jpg` },
      { id: "7", url: `${CDNUrl}/amani-7.jpg` },
      { id: "8", url: `${CDNUrl}/amani-8.jpg` },
      { id: "9", url: `${CDNUrl}/amani-9.jpg` },
      { id: "10", url: `${CDNUrl}/amani-10.jpg` },
      { id: "11", url: `${CDNUrl}/amani-11.jpg` },
    ],
    title: "AMANI DRESS",
    category: "Igbatuntun Collection",
    description: <AmaniDesc />,
    link: "igbatuntun-collection/amani-dress",
    price: 48000,
    priceGBP: undefined,
    priceCAD: 54,
  },
  {
    id: "ayomide-set",
    media: [
      { id: "1", url: `${CDNUrl}/ayomide-1.jpg` },
      { id: "2", url: `${CDNUrl}/ayomide-2.jpg` },
      { id: "3", url: `${CDNUrl}/ayomide-3.jpg` },
      { id: "4", url: `${CDNUrl}/ayomide-4.jpg` },
      { id: "5", url: `${CDNUrl}/ayomide-5.jpg` },
      { id: "6", url: `${CDNUrl}/ayomide-6.jpg` },
      { id: "7", url: `${CDNUrl}/ayomide-7.jpg` },
      { id: "8", url: `${CDNUrl}/ayomide-8.jpg` },
      { id: "9", url: `${CDNUrl}/ayomide-9.jpg` },
      { id: "10", url: `${CDNUrl}/ayomide-10.jpg` },
    ],
    title: "AYOMIDE SET",
    category: "Igbatuntun Collection",
    description: <AyomideDesc />,
    link: "igbatuntun-collection/ayomide-set",
    price: 69000,
    priceGBP: undefined,
    priceCAD: 77,
  },
  {
    id: "favor-set",
    media: [
      { id: "1", url: `${CDNUrl}/favor-1.jpg` },
      { id: "2", url: `${CDNUrl}/favor-2.jpg` },
    ],
    title: "FAVOR SET",
    category: "Igbatuntun Collection",
    description: <FavorDesc />,
    link: "igbatuntun-collection/favor-set",
    price: 73000,
    priceGBP: undefined,
    priceCAD: 80,
  },
  {
    id: "ibukun-set",
    media: [
      { id: "1", url: `${CDNUrl}/ibukun-1.jpeg` },
      { id: "2", url: `${CDNUrl}/ibukun-2.jpeg` },
      { id: "3", url: `${CDNUrl}/ibukun-3.jpeg` },
      { id: "4", url: `${CDNUrl}/ibukun-4.jpeg` },
    ],
    title: "IBUKUN SET",
    category: "Igbatuntun Collection",
    description: <IbukunDesc />,
    link: "igbatuntun-collection/ibukun-set",
    price: 70000,
    priceGBP: undefined,
    priceCAD: 78,
  },
  {
    id: "ife-set",
    media: [
      { id: "1", url: `${CDNUrl}/ife-1.jpg` },
      { id: "2", url: `${CDNUrl}/ife-2.jpg` },
      { id: "3", url: `${CDNUrl}/ife-3.jpg` },
      { id: "4", url: `${CDNUrl}/ife-4.jpg` },
      { id: "5", url: `${CDNUrl}/ife-5.jpg` },
      { id: "6", url: `${CDNUrl}/ife-6.jpg` },
      { id: "7", url: `${CDNUrl}/ife-7.jpg` },
      { id: "8", url: `${CDNUrl}/ife-8.jpg` },
      { id: "9", url: `${CDNUrl}/ife-9.jpg` },
      { id: "10", url: `${CDNUrl}/ife-10.jpg` },
      { id: "11", url: `${CDNUrl}/ife-11.jpg` },
    ],
    title: "IFE SET",
    category: "Igbatuntun Collection",
    description: <IfeDesc />,
    link: "igbatuntun-collection/ife-set",
    price: 64000,
    priceGBP: undefined,
    priceCAD: 73,
  },
  {
    id: "irawo-dress",
    media: [
      { id: "1", url: `${CDNUrl}/irawo-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/irawo-dress-2.jpg` },
    ],
    title: "IRAWO DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/irawo-dress",
    price: 75000,
    priceGBP: undefined,
    priceCAD: 84,
  },
  {
    id: "irawo-set",
    media: [
      { id: "1", url: `${CDNUrl}/irawo-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/irawo-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/irawo-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/irawo-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/irawo-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/irawo-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/irawo-set-7.jpg` },
      { id: "8", url: `${CDNUrl}/irawo-set-8.jpg` },
      { id: "9", url: `${CDNUrl}/irawo-set-9.jpg` },
      { id: "10", url: `${CDNUrl}/irawo-set-10.jpg` },
    ],
    title: "IRAWO SET",
    category: "Igbatuntun Collection",
    description: <IrawoSetDesc />,
    link: "igbatuntun-collection/irawo-set",
    priceVariations: [
      { style: "Irawo jacket set", price: 94000, priceGBP: undefined, priceCAD: 105 },
      { style: "Irawo blouse set", price: 80000, priceGBP: undefined, priceCAD: 89 },
      { style: "Irawo dress set", price: 82000, priceGBP: undefined, priceCAD: 92 },
    ],
  },
  {
    id: "iyanu-dress",
    media: [
      { id: "1", url: `${CDNUrl}/iyanu-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/iyanu-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/iyanu-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/iyanu-dress-4.jpg` },
      { id: "5", url: `${CDNUrl}/iyanu-dress-5.jpg` },
      { id: "6", url: `${CDNUrl}/iyanu-dress-6.jpg` },
      { id: "7", url: `${CDNUrl}/iyanu-dress-7.jpg` },
      { id: "8", url: `${CDNUrl}/iyanu-dress-8.jpg` },
      { id: "9", url: `${CDNUrl}/iyanu-dress-9.jpg` },
      { id: "10", url: `${CDNUrl}/iyanu-dress-10.jpg` },
      { id: "11", url: `${CDNUrl}/iyanu-dress-11.jpg` },
    ],
    title: "IYANU DRESS",
    category: "Igbatuntun Collection",
    description: <IyanuDesc />,
    link: "igbatuntun-collection/iyanu-dress",
    price: 70000,
    priceGBP: undefined,
    priceCAD: 78,
  },
  {
    id: "kuku-set",
    media: [
      { id: "1", url: `${CDNUrl}/kuku-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/kuku-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/kuku-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/kuku-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/kuku-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/kuku-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/kuku-set-7.jpg` },
      { id: "8", url: `${CDNUrl}/kuku-set-8.jpg` },
      { id: "9", url: `${CDNUrl}/kuku-set-9.jpg` },
      { id: "10", url: `${CDNUrl}/kuku-set-10.jpg` },
    ],
    title: "KUKU SET",
    category: "Igbatuntun Collection",
    description: <KukuDesc />,
    link: "igbatuntun-collection/kuku-set",
    price: 60000,
    priceGBP: undefined,
    priceCAD: 65,
  },
  {
    id: "oreoluwa-dress",
    media: [
      { id: "1", url: `${CDNUrl}/oreoluwa-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/oreoluwa-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/oreoluwa-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/oreoluwa-dress-4.jpg` },
      { id: "5", url: `${CDNUrl}/oreoluwa-dress-5.jpg` },
      { id: "6", url: `${CDNUrl}/oreoluwa-dress-6.jpg` },
      { id: "7", url: `${CDNUrl}/oreoluwa-dress-7.jpg` },
    ],
    title: "OREOLUWA DRESS",
    category: "Igbatuntun Collection",
    description: <OreoluwaDesc />,
    link: "igbatuntun-collection/oreoluwa-dress",
    price: 62000,
    priceGBP: undefined,
    priceCAD: 71,
  },
  {
    id: "one-thing",
    media: [
      { id: "1", url: `${CDNUrl}/one-thing-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/one-thing-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/one-thing-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/one-thing-dress-4.jpg` },
      { id: "5", url: `${CDNUrl}/one-thing-dress-5.jpg` },
      { id: "6", url: `${CDNUrl}/one-thing-dress-6.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-7.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-8.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-9.jpg` },
      { id: "7", url: `${CDNUrl}/one-thing-dress-10.jpg` },
    ],
    title: "ONE THING DRESS",
    category: "Igbatuntun Collection",
    description: <OneThingDesc />,
    link: "igbatuntun-collection/one-thing",
    price: 60000,
    priceGBP: undefined,
    priceCAD: 65,
  },
  {
    id: "isinmi-1-dress",
    media: [
      { id: "1", url: `${CDNUrl}/isinmi-dress-1.jpg` },
      { id: "2", url: `${CDNUrl}/isinmi-dress-5.jpg` },
      { id: "3", url: `${CDNUrl}/isinmi-dress-6.jpg` },
      { id: "4", url: `${CDNUrl}/isinmi-dress-8.jpg` },
      { id: "5", url: `${CDNUrl}/isinmi-dress-10.jpg` },
      { id: "6", url: `${CDNUrl}/isinmi-dress-11.jpg` },
      { id: "7", url: `${CDNUrl}/isinmi-dress-12.jpg` },
      { id: "8", url: `${CDNUrl}/isinmi-dress-15.jpg` },
      { id: "9", url: `${CDNUrl}/isinmi-dress-17.jpg` },
      { id: "10", url: `${CDNUrl}/isinmi-dress-18.jpg` },
      { id: "11", url: `${CDNUrl}/isinmi-dress-20.jpg` },
    ],
    title: "ISINMI 1 DRESS",
    category: "Igbatuntun Collection",
    description: <Isinmi1Desc />,
    link: "igbatuntun-collection/isinmi-1-dress",
    price: 45000,
    priceGBP: undefined,
    priceCAD: 50,
  },
  {
    id: "isinmi-2-dress",
    media: [
      { id: "2", url: `${CDNUrl}/isinmi-dress-2.jpg` },
      { id: "3", url: `${CDNUrl}/isinmi-dress-3.jpg` },
      { id: "4", url: `${CDNUrl}/isinmi-dress-4.jpg` },
      { id: "7", url: `${CDNUrl}/isinmi-dress-7.jpg` },
      { id: "9", url: `${CDNUrl}/isinmi-dress-9.jpg` },
      { id: "13", url: `${CDNUrl}/isinmi-dress-13.jpg` },
      { id: "14", url: `${CDNUrl}/isinmi-dress-14.jpg` },
      { id: "16", url: `${CDNUrl}/isinmi-dress-16.jpg` },
      { id: "19", url: `${CDNUrl}/isinmi-dress-19.jpg` },
      { id: "21", url: `${CDNUrl}/isinmi-dress-21.jpg` },
    ],
    title: "ISINMI 2 DRESS",
    category: "Igbatuntun Collection",
    description: <Isinmi2Desc />,
    link: "igbatuntun-collection/isinmi-2-dress",
    price: 45000,
    priceGBP: undefined,
    priceCAD: 50,
  },
  {
    id: "ayo-set",
    media: [
      { id: "1", url: `${CDNUrl}/ayo-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/ayo-set-2.jpg` },
      { id: "3", url: `${CDNUrl}/ayo-set-3.jpg` },
      { id: "4", url: `${CDNUrl}/ayo-set-4.jpg` },
      { id: "5", url: `${CDNUrl}/ayo-set-5.jpg` },
      { id: "6", url: `${CDNUrl}/ayo-set-6.jpg` },
      { id: "7", url: `${CDNUrl}/ayo-set-7.jpg` },
    ],
    title: "AYO SET",
    category: "Igbatuntun Collection",
    description: <AyoDesc />,
    link: "igbatuntun/ayo-set",
    priceVariations: [
      { style: "Ayo Set", price: 56000, priceGBP: undefined, priceCAD: 63 },
      { style: "Ayo Pant Set", price: 60000, priceGBP: undefined, priceCAD: 65 },
    ],
  },

  // ===== Nuach Collection =====
  {
    id: "adunbarin-set",
    media: [
      { id: "1", url: `${CDNUrl}/adunbarin-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/adunbarin-1.jpg` },
      { id: "3", url: `${CDNUrl}/adunbarin-2.jpg` },
      { id: "4", url: `${CDNUrl}/adunbarin-3.jpg` },
      { id: "5", url: `${CDNUrl}/adunbarin-4.jpg` },
      { id: "6", url: `${CDNUrl}/adunbarin-5.jpg` },
      { id: "7", url: `${CDNUrl}/adunbarin-6.jpg` },
      { id: "8", url: `${CDNUrl}/adunbarin-7.jpg` },
    ],
    title: "ADUNBARIN SET",
    category: "Nuach Collection",
    description: <AdunbarinDesc />,
    link: "nuach/adunbarin-set",
    price: 61000,
    priceGBP: undefined,
    priceCAD: 68,
  },
  {
    id: "alheri-set",
    media: [
      { id: "1", url: `${CDNUrl}/alheri-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/alheri-1.png` },
      { id: "3", url: `${CDNUrl}/alheri-2.jpeg` },
      { id: "4", url: `${CDNUrl}/alheri-3.png` },
      { id: "5", url: `${CDNUrl}/alheri-4.png` },
      { id: "6", url: `${CDNUrl}/alheri-5.png` },
      { id: "7", url: `${CDNUrl}/alheri-6.png` },
    ],
    title: "ALHERI SET",
    category: "Nuach Collection",
    description: <AlheriDesc />,
    link: "nuach/alheri-set",
    price: 52500,
    priceGBP: undefined,
    priceCAD: 59,
  },
  {
    id: "alora-dress",
    media: [
      { id: "1", url: `${CDNUrl}/alora-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/alora-3.png` },
      { id: "3", url: `${CDNUrl}/alora-4.png` },
      { id: "4", url: `${CDNUrl}/alora-2.png` },
      { id: "5", url: `${CDNUrl}/alora-1.png` },
      { id: "6", url: `${CDNUrl}/alora-5.png` },
      { id: "7", url: `${CDNUrl}/alora-6.png` },
    ],
    title: "ALORA DRESS",
    category: "Nuach Collection",
    description: <AloraDesc />,
    link: "nuach/alora-dress",
    price: 59500,
    priceGBP: undefined,
    priceCAD: 67,
  },
  {
    id: "ariella-dress",
    media: [
      { id: "1", url: `${CDNUrl}/ariella-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/ariella-1.png` },
      { id: "3", url: `${CDNUrl}/ariella-2.png` },
      { id: "4", url: `${CDNUrl}/ariella-3.png` },
      { id: "5", url: `${CDNUrl}/ariella-8.jpg` },
      { id: "6", url: `${CDNUrl}/ariella-4.png` },
      { id: "7", url: `${CDNUrl}/ariella-5.png` },
      { id: "8", url: `${CDNUrl}/ariella-6.png` },
      { id: "9", url: `${CDNUrl}/ariella-7.png` },
    ],
    title: "ARIELLA DRESS",
    category: "Nuach Collection",
    description: <AriellaDesc />,
    link: "nuach/ariella-dress",
    price: 65000,
    priceGBP: undefined,
    priceCAD: 71,
  },
  {
    id: "atofarati-set",
    media: [
      { id: "1", url: `${CDNUrl}/atofarati-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/atofarati-1.png` },
      { id: "3", url: `${CDNUrl}/atofarati-2.png` },
      { id: "4", url: `${CDNUrl}/atofarati-3.png` },
      { id: "5", url: `${CDNUrl}/atofarati-4.png` },
      { id: "6", url: `${CDNUrl}/atofarati-5.png` },
      { id: "7", url: `${CDNUrl}/atofarati-6.png` },
      { id: "8", url: `${CDNUrl}/atofarati-7.png` },
      { id: "9", url: `${CDNUrl}/atofarati-8.png` },
      { id: "10", url: `${CDNUrl}/atofarati-9.png` },
      { id: "11", url: `${CDNUrl}/atofarati-10.png` },
    ],
    title: "ATOFARATI SET",
    category: "Nuach Collection",
    description: <AtofaratiDesc />,
    link: "nuach/atofarati-set",
    priceVariations: [
      { style: "Adire and Asooke", price: 57500, priceGBP: undefined, priceCAD: 64 },
      { style: "Asooke and Taffeta", price: 58000, priceGBP: undefined, priceCAD: 65 },
      { style: "2 Colored Taffeta", price: 55000, priceGBP: undefined, priceCAD: 61 },
      { style: "Full Asooke", price: 92500, priceGBP: undefined, priceCAD: 106 },
    ],
  },
  {
    id: "babara-dress",
    media: [
      { id: "1", url: `${CDNUrl}/barabara-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/barabara-1.jpeg` },
      { id: "3", url: `${CDNUrl}/barabara-2.png` },
      { id: "4", url: `${CDNUrl}/barabara-3.png` },
      { id: "5", url: `${CDNUrl}/barabara-11.jpg` },
      { id: "6", url: `${CDNUrl}/barabara-12.jpg` },
      { id: "7", url: `${CDNUrl}/barabara-13.jpg` },
      { id: "8", url: `${CDNUrl}/barabara-4.png` },
      { id: "9", url: `${CDNUrl}/barabara-5.png` },
      { id: "10", url: `${CDNUrl}/barabara-6.png` },
      { id: "11", url: `${CDNUrl}/barabara-7.png` },
      { id: "12", url: `${CDNUrl}/barabara-9.png` },
      { id: "13", url: `${CDNUrl}/barabara-10.png` },
    ],
    title: "BABARA DRESS",
    category: "Nuach Collection",
    description: <BabaraDesc />,
    link: "nuach/babara-dress",
    priceVariations: [
      { style: "Flowered Mikado", price: 68500, priceGBP: undefined, priceCAD: 77 },
      { style: "Adire Cotton", price: 57000, priceGBP: undefined, priceCAD: 63.5 },
      { style: "Adire Crepe", price: 57000, priceGBP: undefined, priceCAD: 63.5 },
    ],
  },
  {
    id: "danielle-set",
    media: [
      { id: "1", url: `${CDNUrl}/danielle-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/danielle-1.png` },
      { id: "3", url: `${CDNUrl}/danielle-2.png` },
      { id: "4", url: `${CDNUrl}/danielle-3.png` },
      { id: "5", url: `${CDNUrl}/danielle-4.png` },
      { id: "6", url: `${CDNUrl}/danielle-5.png` },
      { id: "7", url: `${CDNUrl}/danielle-6.png` },
      { id: "8", url: `${CDNUrl}/danielle-7.png` },
      { id: "9", url: `${CDNUrl}/danielle-8.jpeg` },
      { id: "10", url: `${CDNUrl}/danielle-9.png` },
      { id: "11", url: `${CDNUrl}/danielle-10.png` },
    ],
    title: "DANIELLE SET",
    category: "Nuach Collection",
    description: <DanielleDesc />,
    link: "nuach/danielle-set",
    priceVariations: [
      { style: "Dress Set", price: 82500, priceGBP: undefined, priceCAD: 94 },
      { style: "Skirt Set", price: 68500, priceGBP: undefined, priceCAD: 79 },
    ],
  },
  {
    id: "ileri-boubou",
    media: [
      { id: "1", url: `${CDNUrl}/ileri-boubou-1.mp4` },
      { id: "2", url: `${CDNUrl}/ilerioluwa-2.png` },
      { id: "3", url: `${CDNUrl}/ilerioluwa-3.png` },
      { id: "4", url: `${CDNUrl}/ilerioluwa-6.jpg` },
      { id: "5", url: `${CDNUrl}/ilerioluwa-7.jpg` },
      { id: "6", url: `${CDNUrl}/ilerioluwa-4.png` },
      { id: "7", url: `${CDNUrl}/ilerioluwa-5.png` },
      { id: "8", url: `${CDNUrl}/ilerioluwa-1.png` },
    ],
    title: "ILERIOLUWA SET/BOUBOU",
    category: "Nuach Collection",
    description: <IlerioluwaDesc />,
    link: "nuach/ileri-boubou",
    priceVariations: [
      { style: "Set", price: 58000, priceGBP: undefined, priceCAD: 65 },
      { style: "Boubou in Mikado", price: 42000, priceGBP: undefined, priceCAD: 47 },
      { style: "Boubou in Adire", price: 42500, priceGBP: undefined, priceCAD: 48 },
    ],
  },
  {
    id: "iye-dress",
    media: [
      { id: "1", url: `${CDNUrl}/iye-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/iye-1.png` },
      { id: "3", url: `${CDNUrl}/iye-2.png` },
      { id: "4", url: `${CDNUrl}/iye-3.png` },
      { id: "5", url: `${CDNUrl}/iye-4.png` },
      { id: "6", url: `${CDNUrl}/iye-5.png` },
      { id: "7", url: `${CDNUrl}/iye-6.png` },
      { id: "8", url: `${CDNUrl}/iye-7.png` },
      { id: "9", url: `${CDNUrl}/iye-8.png` },
      { id: "10", url: `${CDNUrl}/iye-9.png` },
      { id: "11", url: `${CDNUrl}/iye-10.png` },
      { id: "12", url: `${CDNUrl}/iye-11.png` },
      { id: "13", url: `${CDNUrl}/iye-12.png` },
    ],
    title: "IYE DRESS",
    category: "Nuach Collection",
    description: <IyeDesc />,
    link: "nuach/iye-dress",
    priceVariations: [
      { style: "Fitted (Plain Color)", price: 55000, priceGBP: undefined, priceCAD: 62 },
      { style: "Fitted (Adire)", price: 56000, priceGBP: undefined, priceCAD: 62.5 },
      { style: "Flair (Adire)", price: 68000, priceGBP: undefined, priceCAD: 77 },
    ],
  },
  {
    id: "keziah-set",
    media: [
      { id: "1", url: `${CDNUrl}/keziah-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/keziah-1.png` },
      { id: "3", url: `${CDNUrl}/keziah-2.png` },
      { id: "4", url: `${CDNUrl}/keziah-3.png` },
      { id: "5", url: `${CDNUrl}/keziah-4.png` },
      { id: "6", url: `${CDNUrl}/keziah-5.png` },
      { id: "7", url: `${CDNUrl}/keziah-6.png` },
      { id: "8", url: `${CDNUrl}/keziah-7.png` },
      { id: "9", url: `${CDNUrl}/keziah-8.png` },
      { id: "10", url: `${CDNUrl}/keziah-9.png` },
      { id: "11", url: `${CDNUrl}/keziah-10.png` },
    ],
    title: "KEZIAH SET",
    category: "Nuach Collection",
    description: <KeziahDesc />,
    link: "nuach/keziah-set",
    priceVariations: [
      { style: "2 Colored Taffeta (Pant Set)", price: 55500, priceGBP: undefined, priceCAD: 61 },
      { style: "Adire (Pant Set)", price: 54500, priceGBP: undefined, priceCAD: 60.5 },
      { style: "Adire (Skirt Set)", price: 53500, priceGBP: undefined, priceCAD: 59 },
      { style: "Plain Color (Pant Set)", price: 51500, priceGBP: undefined, priceCAD: 57 },
    ],
  },
  {
    id: "shalom-set",
    media: [
      { id: "1", url: `${CDNUrl}/shalom-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/shalom-1.png` },
      { id: "3", url: `${CDNUrl}/shalom-2.png` },
      { id: "4", url: `${CDNUrl}/shalom-3.png` },
      { id: "5", url: `${CDNUrl}/shalom-4.png` },
      { id: "6", url: `${CDNUrl}/shalom-5.png` },
    ],
    title: "SHALOM SET",
    category: "Nuach Collection",
    description: <ShalomDesc />,
    link: "nuach/shalom-set",
    priceVariations: [
      { style: "In Adire", price: 57500, priceGBP: undefined, priceCAD: 64 },
      { style: "Plain Color & Sunray", price: 56500, priceGBP: undefined, priceCAD: 63 },
    ],
  },
  {
    id: "tamara-dress",
    media: [
      { id: "1", url: `${CDNUrl}/tamara-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/tamara-1.jpg` },
      { id: "3", url: `${CDNUrl}/tamara-3.jpg` },
      { id: "4", url: `${CDNUrl}/tamara-2.jpg` },
      { id: "5", url: `${CDNUrl}/tamara-4.jpg` },
      { id: "6", url: `${CDNUrl}/tamara-5.jpg` },
      { id: "7", url: `${CDNUrl}/tamara-6.jpg` },
      { id: "8", url: `${CDNUrl}/tamara-7.jpg` },
    ],
    title: "TAMARA DRESS",
    category: "Nuach Collection",
    description: <TamaraDesc />,
    link: "nuach/tamara-dress",
    price: 46500,
    priceGBP: undefined,
    priceCAD: 55,
  },
  {
    id: "tirzah-dress",
    media: [
      { id: "1", url: `${CDNUrl}/tirzah-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/tirzah-1.png` },
      { id: "3", url: `${CDNUrl}/tirzah-2.png` },
      { id: "4", url: `${CDNUrl}/tirzah-3.png` },
      { id: "5", url: `${CDNUrl}/tirzah-4.png` },
      { id: "6", url: `${CDNUrl}/tirzah-5.png` },
      { id: "7", url: `${CDNUrl}/tirzah-6.png` },
      { id: "8", url: `${CDNUrl}/tirzah-7.png` },
      { id: "9", url: `${CDNUrl}/tirzah-8.png` },
      { id: "10", url: `${CDNUrl}/tirzah-9.png` },
      { id: "11", url: `${CDNUrl}/tirzah-10.png` },
      { id: "12", url: `${CDNUrl}/tirzah-11.png` },
    ],
    title: "TIRZAH DRESS",
    category: "Nuach Collection",
    description: <TirzahDesc />,
    link: "nuach/tirzah-dress",
    priceVariations: [
      { style: "Plain Color Long Dress", price: 62000, priceGBP: undefined, priceCAD: 70.5 },
      { style: "Adire Silk", price: 57500, priceGBP: undefined, priceCAD: 63.5 },
      { style: "Adire Crepe Boubou", price: 44000, priceGBP: undefined, priceCAD: 50 },
    ],
  },
  {
    id: "hana-set",
    media: [
      { id: "1", url: `${CDNUrl}/hana-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/hana-1.jpg` },
      { id: "3", url: `${CDNUrl}/hana-2.jpg` },
      { id: "4", url: `${CDNUrl}/hana-3.jpg` },
      { id: "5", url: `${CDNUrl}/hana-4.jpg` },
      { id: "6", url: `${CDNUrl}/hana-5.jpg` },
      { id: "7", url: `${CDNUrl}/hana-6.jpg` },
    ],
    title: "HANA SET",
    category: "Nuach Collection",
    description: <HanaDesc />,
    link: "nuach/hana-set",
    price: 72000,
    priceGBP: undefined,
    priceCAD: 82.5,
  },

  {
    id: "moremi-set",
    media: [
      { id: "1", url: `${CDNUrl}/moremi-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/moremi-1.jpg` },
      { id: "3", url: `${CDNUrl}/moremi-2.jpg` },
      { id: "4", url: `${CDNUrl}/moremi-3.jpg` },
      { id: "5", url: `${CDNUrl}/moremi-4.jpg` },
      { id: "6", url: `${CDNUrl}/moremi-5.jpg` },
    ],
    title: "MOREMI SET",
    category: "Nuach Collection",
    description: <MoremiDesc />,
    link: "nuach/moremi-set",
    price: 50000,
    priceGBP: undefined,
    priceCAD: 56,
  },

  {
    id: "zuriel-set",
    media: [
      { id: "1", url: `${CDNUrl}/zuriel-set-1.mp4` },
      { id: "2", url: `${CDNUrl}/zuriel-1.jpg` },
      { id: "3", url: `${CDNUrl}/zuriel-3.jpg` },
      { id: "4", url: `${CDNUrl}/zuriel-2.jpg` },
      { id: "5", url: `${CDNUrl}/zuriel-5.jpg` },
      { id: "6", url: `${CDNUrl}/zuriel-4.jpg` },
      { id: "7", url: `${CDNUrl}/zuriel-6.jpg` },
      { id: "8", url: `${CDNUrl}/zuriel-7.jpg` },
    ],
    title: "ZURIEL SET",
    category: "Nuach Collection",
    description: <ZurielDesc />,
    link: "nuach/zuriel-set",
    priceVariations: [
      { style: "Embellished Crepe", price: 56000, priceGBP: undefined, priceCAD: 65 },
      { style: "Plain and Adire Pants", price: 47000, priceGBP: undefined, priceCAD: 54 },
    ],
  },

  {
    id: "ewa-set",
    media: [
      { id: "1", url: `${CDNUrl}/ewa-set-1.jpg` },
      { id: "2", url: `${CDNUrl}/ewa-set-4.jpg` },
      { id: "3", url: `${CDNUrl}/ewa-set-2.jpg` },
      { id: "4", url: `${CDNUrl}/ewa-set-7.jpg` },
      { id: "5", url: `${CDNUrl}/ewa-set-3.jpg` },
      { id: "6", url: `${CDNUrl}/ewa-set-5.jpg` },
      { id: "7", url: `${CDNUrl}/ewa-set-6.jpg` },
      { id: "8", url: `${CDNUrl}/ewa-set-8.jpg` },
      { id: "9", url: `${CDNUrl}/ewa-set-9.jpg` },
    ],
    title: "EWA SET",
    category: "Nuach Collection",
    description: <EwaDesc />,
    link: "nuach/ewa-set",
    price: 54000,
    priceGBP: undefined,
    priceCAD: 61,
  },

  {
    id: "ewa-boubou",
    media: [
      { id: "1", url: `${CDNUrl}/ewa-boubou-1.jpg` },
      { id: "2", url: `${CDNUrl}/ewa-boubou-2.jpg` },
      { id: "3", url: `${CDNUrl}/ewa-boubou-3.jpg` },
      { id: "4", url: `${CDNUrl}/ewa-boubou-4.jpg` },
      { id: "5", url: `${CDNUrl}/ewa-boubou-5.jpg` },
      { id: "6", url: `${CDNUrl}/ewa-boubou-6.jpg` },
      { id: "7", url: `${CDNUrl}/ewa-boubou-7.jpg` },
      { id: "8", url: `${CDNUrl}/ewa-boubou-8.jpg` },
      { id: "9", url: `${CDNUrl}/ewa-boubou-9.jpg` },
      { id: "10", url: `${CDNUrl}/ewa-boubou-10.jpg` },
      { id: "11", url: `${CDNUrl}/ewa-boubou-11.jpg` },
    ],
    title: "EWA BOUBOU",
    category: "Nuach Collection",
    description: <EwaBouBouDesc />,
    link: "nuach/ewa-boubou",
    price: 46000,
    priceGBP: undefined,
    priceCAD: 51.5,
  },
  {
    id: "mirabel-dress",
    media: [
      { id: "1", url: `${CDNUrl}/mirabel-dress-1.mp4` },
      { id: "2", url: `${CDNUrl}/mirabel-dress-1.jpg` },
      { id: "3", url: `${CDNUrl}/mirabel-dress-2.jpg` },
    ],
    title: "MIRABEL DRESS",
    category: "Ready To Wear",
    description: <MirabelDesc />,
    link: "ready-to-wear/mirabel-dress",
    price: 65000,
    priceGBP: undefined,
    priceCAD: 71,
  },
];
