import {
  AlheriDesc,
  AloraDesc,
  AriellaDesc,
  AtofaratiDesc,
  BarabaraDesc,
  DanielleDesc,
  IlerioluwaDesc,
  IyeDesc,
  KeziahDesc,
  ShalomDesc,
  TamaraDesc,
  TirzahDesc,
} from "./description";
import { ReactNode } from "react";

export type CollectionItem = {
  id: string;
  media: { id: string; url: string }[];
  title: string;
  category: string;
  description: string | ReactNode;
  link: string;
};

export const collectionsData: CollectionItem[] = [
  // ===== Bridals Collection =====
  {
    id: "bridal-1",
    media: [
      { id: "1", url: "/bridals-12.JPG" },
      { id: "2", url: "/bridals-14.JPG" },
      { id: "3", url: "/bridals-8.JPG" },
      { id: "4", url: "/bridals-10.JPG" },
      { id: "5", url: "/bridals-7.JPG" },
      { id: "6", url: "/bridals-4.JPG" },
      { id: "7", url: "/bridals-9.JPG" },
      { id: "8", url: "/bridals-11.JPG" },
      { id: "9", url: "/bridals-18.JPG" },
      { id: "10", url: "/bridals-16.JPG" },
      { id: "11", url: "/bridals-6.JPG" },
      { id: "12", url: "/bridals-15.JPG" },
    ],
    title: "BRIDAL WEAR",
    category: "Bridals",
    description:
      "A timeless lace bridal gown featuring delicate floral patterns and a flowing silhouette.",
    link: "bridals/bridal-1",
  },
  {
    id: "bridal-2",
    media: [
      { id: "1", url: "/bridals-33.JPG" },
      { id: "2", url: "/bridals-32.JPG" },
      { id: "3", url: "/bridals-37.JPG" },
      { id: "4", url: "/bridals-34.JPG" },
      { id: "5", url: "/bridals-31.JPG" },
      { id: "6", url: "/bridals-5.JPG" },
      { id: "7", url: "/bridals-28.JPG" },
      { id: "8", url: "/bridals-29.JPG" },
      { id: "9", url: "/bridals-30.JPG" },
    ],
    title: "BRIDAL WEAR",
    category: "Bridals",
    description:
      "This figure-hugging mermaid dress is perfect for brides seeking a sleek, contemporary look.",
    link: "bridals/bridal-2",
  },
  {
    id: "bridal-3",
    media: [
      { id: "1", url: "/bridals-26.JPG" },
      { id: "2", url: "/bridals-44.JPG" },
      { id: "3", url: "/bridals-27.JPG" },
      { id: "4", url: "/bridals-3.JPG" },
      { id: "5", url: "/bridals-1.JPG" },
    ],
    title: "BRIDAL WEAR",
    category: "Bridals",
    description:
      "A dreamy ball gown with off-shoulder sleeves and a full tulle skirt for a fairytale moment.",
    link: "bridals/bridal-3",
  },
  {
    id: "bridal-4",
    media: [
      { id: "1", url: "/bridals-42.JPG" },
      { id: "2", url: "/bridals-41.JPG" },
      { id: "3", url: "/bridals-40.JPG" },
      { id: "4", url: "/bridals-38.JPG" },
    ],
    title: "BRIDAL WEAR",
    category: "Bridals",
    description:
      "Charming vintage-inspired dress with lace detailing and a romantic neckline.",
    link: "bridals/bridal-4",
  },
  {
    id: "bridal-5",
    media: [
      { id: "1", url: "/bridals-23.JPG" },
      { id: "2", url: "/bridals-22.JPG" },
      { id: "3", url: "/bridals-24.JPG" },
    ],
    title: "BRIDAL WEAR",
    category: "Bridals",
    description:
      "Sleek and simple silk A-line gown with a minimalist design and elegant flow.",
    link: "bridals/bridal-5",
  },
  {
    id: "bridal-6",
    media: [
      { id: "1", url: "/bridals-2.JPG" },
      { id: "2", url: "/bridals-21.JPG" },
      { id: "3", url: "/bridals-43.JPG" },
    ],
    title: "BRIDAL WEAR",
    category: "Bridals",
    description:
      "Free-spirited boho bridal dress with flowing fabrics and earthy details.",
    link: "bridals/bridal-6",
  },

  // ===== Igbatuntun Collection =====
  {
    id: "ire-set",
    media: [
      { id: "1", url: "/ire-set-1.jpg" },
      { id: "2", url: "/ire-set-2.jpg" },
      { id: "3", url: "/ire-set-3.jpg" },
      { id: "4", url: "/ire-set-4.jpg" },
      { id: "5", url: "/ire-set-5.jpg" },
      { id: "6", url: "/ire-set-6.jpg" },
      { id: "7", url: "/ire-set-7.jpg" },
    ],
    title: "IRE SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/ire-set",
  },
  {
    id: "amani-dress",
    media: [
      { id: "1", url: "/amani-1.jpg" },
      { id: "2", url: "/amani-2.jpg" },
      { id: "3", url: "/amani-3.jpg" },
      { id: "4", url: "/amani-4.jpg" },
      { id: "5", url: "/amani-5.jpg" },
      { id: "6", url: "/amani-6.jpg" },
      { id: "7", url: "/amani-7.jpg" },
      { id: "8", url: "/amani-8.jpg" },
      { id: "9", url: "/amani-9.jpg" },
      { id: "10", url: "/amani-10.jpg" },
      { id: "11", url: "/amani-11.jpg" },
    ],
    title: "AMANI DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/amani-dress",
  },
  {
    id: "ayomide-set",
    media: [
      { id: "1", url: "/ayomide-1.jpg" },
      { id: "2", url: "/ayomide-2.jpg" },
      { id: "3", url: "/ayomide-3.jpg" },
      { id: "4", url: "/ayomide-4.jpg" },
      { id: "5", url: "/ayomide-5.jpg" },
      { id: "6", url: "/ayomide-6.jpg" },
      { id: "7", url: "/ayomide-7.jpg" },
      { id: "8", url: "/ayomide-8.jpg" },
      { id: "9", url: "/ayomide-9.jpg" },
      { id: "10", url: "/ayomide-10.jpg" },
    ],
    title: "AYOMIDE SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/ayomide-set",
  },
  {
    id: "favor-set",
    media: [
      { id: "1", url: "/favor-1.jpg" },
      { id: "2", url: "/favor-2.jpg" },
    ],
    title: "FAVOR SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/favor-set",
  },
  {
    id: "ibukun-set",
    media: [
      { id: "1", url: "/ibukun-1.jpeg" },
      { id: "2", url: "/ibukun-2.jpeg" },
      { id: "3", url: "/ibukun-3.jpeg" },
      { id: "4", url: "/ibukun-4.jpeg" },
    ],
    title: "IBUKUN SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/ibukun-set",
  },
  {
    id: "ife-set",
    media: [
      { id: "1", url: "/ife-1.jpg" },
      { id: "2", url: "/ife-2.jpg" },
      { id: "3", url: "/ife-3.jpg" },
      { id: "4", url: "/ife-4.jpg" },
      { id: "5", url: "/ife-5.jpg" },
      { id: "6", url: "/ife-6.jpg" },
      { id: "7", url: "/ife-7.jpg" },
      { id: "8", url: "/ife-8.jpg" },
      { id: "9", url: "/ife-9.jpg" },
      { id: "10", url: "/ife-10.jpg" },
      { id: "11", url: "/ife-11.jpg" },
    ],
    title: "IFE SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/ife-set",
  },
  {
    id: "irawo-dress",
    media: [
      { id: "1", url: "/irawo-dress-1.jpg" },
      { id: "2", url: "/irawo-dress-2.jpg" },
    ],
    title: "IRAWO DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/irawo-dress",
  },
  {
    id: "irawo-set",
    media: [
      { id: "1", url: "/irawo-set-1.jpg" },
      { id: "2", url: "/irawo-set-2.jpg" },
      { id: "3", url: "/irawo-set-3.jpg" },
      { id: "4", url: "/irawo-set-4.jpg" },
      { id: "5", url: "/irawo-set-5.jpg" },
      { id: "6", url: "/irawo-set-6.jpg" },
      { id: "7", url: "/irawo-set-7.jpg" },
      { id: "8", url: "/irawo-set-8.jpg" },
      { id: "9", url: "/irawo-set-9.jpg" },
      { id: "10", url: "/irawo-set-10.jpg" },
    ],
    title: "IRAWO SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/irawo-set",
  },
  {
    id: "iyanu-dress",
    media: [
      { id: "1", url: "/iyanu-dress-1.jpg" },
      { id: "2", url: "/iyanu-dress-2.jpg" },
      { id: "3", url: "/iyanu-dress-3.jpg" },
      { id: "4", url: "/iyanu-dress-4.jpg" },
      { id: "5", url: "/iyanu-dress-5.jpg" },
      { id: "6", url: "/iyanu-dress-6.jpg" },
      { id: "7", url: "/iyanu-dress-7.jpg" },
      { id: "8", url: "/iyanu-dress-8.jpg" },
      { id: "9", url: "/iyanu-dress-9.jpg" },
      { id: "10", url: "/iyanu-dress-10.jpg" },
      { id: "11", url: "/iyanu-dress-11.jpg" },
    ],
    title: "IYANU DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/iyanu-dress",
  },
  {
    id: "kuku-set",
    media: [
      { id: "1", url: "/kuku-set-1.jpg" },
      { id: "2", url: "/kuku-set-2.jpg" },
      { id: "3", url: "/kuku-set-3.jpg" },
      { id: "4", url: "/kuku-set-4.jpg" },
      { id: "5", url: "/kuku-set-5.jpg" },
      { id: "6", url: "/kuku-set-6.jpg" },
      { id: "7", url: "/kuku-set-7.jpg" },
      { id: "8", url: "/kuku-set-8.jpg" },
      { id: "9", url: "/kuku-set-9.jpg" },
      { id: "10", url: "/kuku-set-10.jpg" },
    ],
    title: "KUKU SET",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/kuku-set",
  },
  {
    id: "oreoluwa-dress",
    media: [
      { id: "1", url: "/oreoluwa-dress-1.jpg" },
      { id: "2", url: "/oreoluwa-dress-2.jpg" },
      { id: "3", url: "/oreoluwa-dress-3.jpg" },
      { id: "4", url: "/oreoluwa-dress-4.jpg" },
      { id: "5", url: "/oreoluwa-dress-5.jpg" },
      { id: "6", url: "/oreoluwa-dress-6.jpg" },
      { id: "7", url: "/oreoluwa-dress-7.jpg" },
    ],
    title: "OREOLUWA DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/oreoluwa-dress",
  },
  {
    id: "one-thing",
    media: [
      { id: "1", url: "/one-thing-dress-1.jpg" },
      { id: "2", url: "/one-thing-dress-2.jpg" },
      { id: "3", url: "/one-thing-dress-3.jpg" },
      { id: "4", url: "/one-thing-dress-4.jpg" },
      { id: "5", url: "/one-thing-dress-5.jpg" },
      { id: "6", url: "/one-thing-dress-6.jpg" },
      { id: "7", url: "/one-thing-dress-7.jpg" },
      { id: "7", url: "/one-thing-dress-8.jpg" },
      { id: "7", url: "/one-thing-dress-9.jpg" },
      { id: "7", url: "/one-thing-dress-10.jpg" },
    ],
    title: "ONE THING DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/one-thing",
  },
  {
    id: "isinmi-dress",
    media: [
      { id: "1", url: "/isinmi-dress-1.jpg" },
      { id: "2", url: "/isinmi-dress-2.jpg" },
      { id: "3", url: "/isinmi-dress-3.jpg" },
      { id: "4", url: "/isinmi-dress-4.jpg" },
      { id: "5", url: "/isinmi-dress-5.jpg" },
      { id: "6", url: "/isinmi-dress-6.jpg" },
      { id: "7", url: "/isinmi-dress-7.jpg" },
      { id: "8", url: "/isinmi-dress-8.jpg" },
      { id: "9", url: "/isinmi-dress-9.jpg" },
      { id: "10", url: "/isinmi-dress-10.jpg" },
      { id: "11", url: "/isinmi-dress-11.jpg" },
      { id: "12", url: "/isinmi-dress-12.jpg" },
      { id: "13", url: "/isinmi-dress-13.jpg" },
      { id: "14", url: "/isinmi-dress-14.jpg" },
      { id: "15", url: "/isinmi-dress-15.jpg" },
      { id: "16", url: "/isinmi-dress-16.jpg" },
      { id: "17", url: "/isinmi-dress-17.jpg" },
      { id: "18", url: "/isinmi-dress-18.jpg" },
      { id: "19", url: "/isinmi-dress-19.jpg" },
      { id: "20", url: "/isinmi-dress-20.jpg" },
      { id: "21", url: "/isinmi-dress-21.jpg" },
    ],
    title: "ISINMI DRESS",
    category: "Igbatuntun Collection",
    description:
      "Ire Collection Description goes here. This is some sample text to test layout.",
    link: "igbatuntun-collection/isinmi-dress",
  },
  //  Nuach Collection
  {
    id: "alheri-set",
    media: [
      { id: "1", url: "/alheri-set-1.mp4" },
      { id: "2", url: "/alheri-1.png" },
      { id: "3", url: "/alheri-2.jpeg" },
      { id: "4", url: "/alheri-3.png" },
      { id: "5", url: "/alheri-4.png" },
      { id: "6", url: "/alheri-5.png" },
      { id: "7", url: "/alheri-6.png" },
    ],
    title: "ALHERI SET",
    category: "Nuach Collection",
    description: <AlheriDesc />,
    link: "nuach/alheri-set",
  },
  {
    id: "alora-dress",
    media: [
      { id: "1", url: "/alora-dress-1.mp4" },
      { id: "2", url: "/alora-3.png" },
      { id: "3", url: "/alora-4.png" },
      { id: "4", url: "/alora-2.png" },
      { id: "5", url: "/alora-1.png" },
      { id: "6", url: "/alora-5.png" },
      { id: "7", url: "/alora-6.png" },
    ],
    title: "ALORA DRESS",
    category: "Nuach Collection",
    description: <AloraDesc />,
    link: "nuach/alora-dress",
  },
  {
    id: "ariella-dress",
    media: [
      { id: "1", url: "/ariella-dress-1.mp4" },
      { id: "2", url: "/ariella-1.png" },
      { id: "3", url: "/ariella-2.png" },
      { id: "4", url: "/ariella-3.png" },
      { id: "5", url: "/ariella-4.png" },
      { id: "6", url: "/ariella-5.png" },
      { id: "7", url: "/ariella-6.png" },
      { id: "8", url: "/ariella-7.png" },
    ],
    title: "ARIELLA DRESS",
    category: "Nuach Collection",
    description: <AriellaDesc />,
    link: "nuach/ariella-dress",
  },
  {
    id: "atofarati-set",
    media: [
      { id: "1", url: "/atofarati-set-1.mp4" },
      { id: "2", url: "/atofarati-1.png" },
      { id: "3", url: "/atofarati-2.png" },
      { id: "4", url: "/atofarati-3.png" },
      { id: "5", url: "/atofarati-4.png" },
      { id: "6", url: "/atofarati-5.png" },
      { id: "7", url: "/atofarati-6.png" },
      { id: "8", url: "/atofarati-7.png" },
      { id: "9", url: "/atofarati-8.png" },
      { id: "10", url: "/atofarati-9.png" },
      { id: "11", url: "/atofarati-10.png" },
    ],
    title: "ATOFARATI SET",
    category: "Nuach Collection",
    description: <AtofaratiDesc />,
    link: "nuach/atofarati-set",
  },
  {
    id: "barabara-dress",
    media: [
      { id: "1", url: "/barabara-dress-1.mp4" },
      { id: "2", url: "/barabara-1.jpeg" },
      { id: "3", url: "/barabara-2.png" },
      { id: "4", url: "/barabara-3.png" },
      { id: "5", url: "/barabara-4.png" },
      { id: "6", url: "/barabara-5.png" },
      { id: "7", url: "/barabara-6.png" },
      { id: "8", url: "/barabara-7.png" },
      { id: "9", url: "/barabara-8.png" },
      { id: "10", url: "/barabara-9.png" },
      { id: "11", url: "/barabara-10.png" },
    ],
    title: "BARABARA DRESS",
    category: "Nuach Collection",
    description: <BarabaraDesc />,
    link: "nuach/barabara-dress",
  },
  {
    id: "danielle-set",
    media: [
      { id: "1", url: "/danielle-set-1.mp4" },
      { id: "2", url: "/danielle-1.png" },
      { id: "3", url: "/danielle-2.png" },
      { id: "4", url: "/danielle-3.png" },
      { id: "5", url: "/danielle-4.png" },
      { id: "6", url: "/danielle-5.png" },
      { id: "7", url: "/danielle-6.png" },
      { id: "8", url: "/danielle-7.png" },
      { id: "9", url: "/danielle-8.jpeg" },
      { id: "10", url: "/danielle-9.png" },
      { id: "11", url: "/danielle-10.png" },
    ],
    title: "DANIELLE SET",
    category: "Nuach Collection",
    description: <DanielleDesc />,
    link: "nuach/danielle-set",
  },
  {
    id: "ileri-boubou",
    media: [
      { id: "1", url: "/ileri-boubou-1.mp4" },
      { id: "2", url: "/ilerioluwa-1.png" },
      { id: "3", url: "/ilerioluwa-2.png" },
      { id: "4", url: "/ilerioluwa-3.png" },
      { id: "5", url: "/ilerioluwa-4.png" },
      { id: "6", url: "/ilerioluwa-5.png" },
    ],
    title: "ILERIOLUWA SET/BOUBOU",
    category: "Nuach Collection",
    description: <IlerioluwaDesc />,
    link: "nuach/ileri-boubou",
  },
  {
    id: "iye-dress",
    media: [
      { id: "1", url: "/iye-dress-1.mp4" },
      { id: "2", url: "/iye-1.png" },
      { id: "3", url: "/iye-2.png" },
      { id: "4", url: "/iye-3.png" },
      { id: "5", url: "/iye-4.png" },
      { id: "6", url: "/iye-5.png" },
      { id: "7", url: "/iye-6.png" },
      { id: "8", url: "/iye-7.png" },
      { id: "9", url: "/iye-8.png" },
      { id: "10", url: "/iye-9.png" },
      { id: "11", url: "/iye-10.png" },
      { id: "12", url: "/iye-11.png" },
      { id: "13", url: "/iye-12.png" },
    ],
    title: "IYE DRESS",
    category: "Nuach Collection",
    description: <IyeDesc />,
    link: "nuach/iye-dress",
  },
  {
    id: "keziah-set",
    media: [
      { id: "1", url: "/keziah-set-1.mp4" },
      { id: "2", url: "/keziah-1.png" },
      { id: "3", url: "/keziah-2.png" },
      { id: "4", url: "/keziah-3.png" },
      { id: "5", url: "/keziah-4.png" },
      { id: "6", url: "/keziah-5.png" },
      { id: "7", url: "/keziah-6.png" },
      { id: "8", url: "/keziah-7.png" },
      { id: "9", url: "/keziah-8.png" },
      { id: "10", url: "/keziah-9.png" },
      { id: "11", url: "/keziah-10.png" },
    ],
    title: "KEZIAH SET",
    category: "Nuach Collection",
    description: <KeziahDesc />,
    link: "nuach/keziah-set",
  },
  {
    id: "shalom-set",
    media: [
      { id: "1", url: "/shalom-set-1.mp4" },
      { id: "2", url: "/shalom-1.png" },
      { id: "3", url: "/shalom-2.png" },
      { id: "4", url: "/shalom-3.png" },
      { id: "5", url: "/shalom-4.png" },
      { id: "6", url: "/shalom-5.png" },
    ],
    title: "SHALOM SET",
    category: "Nuach Collection",
    description: <ShalomDesc />,
    link: "nuach/shalom-set",
  },
  {
    id: "tamara-dress",
    media: [{ id: "1", url: "/tamara-dress-1.mp4" }],
    title: "TAMARA DRESS",
    category: "Nuach Collection",
    description: <TamaraDesc />,
    link: "nuach/tamara-dress",
  },
  {
    id: "tirzah-dress",
    media: [
      { id: "1", url: "/tirzah-dress-1.mp4" },
      { id: "2", url: "/tirzah-1.png" },
      { id: "3", url: "/tirzah-2.png" },
      { id: "4", url: "/tirzah-3.png" },
      { id: "5", url: "/tirzah-4.png" },
      { id: "6", url: "/tirzah-5.png" },
      { id: "7", url: "/tirzah-6.png" },
      { id: "8", url: "/tirzah-7.png" },
      { id: "9", url: "/tirzah-8.png" },
      { id: "10", url: "/tirzah-9.png" },
      { id: "11", url: "/tirzah-10.png" },
      { id: "12", url: "/tirzah-11.png" },
    ],
    title: "TIRZAH DRESS",
    category: "Nuach Collection",
    description: <TirzahDesc />,
    link: "nuach/tirzah-dress",
  },
];
